// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TokenSale$Type } from "./TokenSale";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TokenSale"]: TokenSale$Type;
    ["contracts/TokenSale.sol:TokenSale"]: TokenSale$Type;
  }
}
