// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20Lockable$Type } from "./ERC20Lockable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Lockable"]: ERC20Lockable$Type;
    ["contracts/ERC20Lockable.sol:ERC20Lockable"]: ERC20Lockable$Type;
  }
}
