// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TokenSwap$Type } from "./TokenSwap";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TokenSwap"]: TokenSwap$Type;
    ["contracts/TokenSwap.sol:TokenSwap"]: TokenSwap$Type;
  }
}
