// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Token$Type } from "./Token";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Token"]: Token$Type;
    ["contracts/Token.sol:Token"]: Token$Type;
  }
}
