// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IToken$Type } from "./IToken";
import { MyERC20Token$Type } from "./MyERC20Token";
import { Standard_Token$Type } from "./Standard_Token";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IToken"]: IToken$Type;
    ["MyERC20Token"]: MyERC20Token$Type;
    ["Standard_Token"]: Standard_Token$Type;
    ["contracts/MyERC20.sol:IToken"]: IToken$Type;
    ["contracts/MyERC20.sol:MyERC20Token"]: MyERC20Token$Type;
    ["contracts/MyERC20.sol:Standard_Token"]: Standard_Token$Type;
  }
}
