// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { dxfc$Type } from "./dxfc";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["dxfc"]: dxfc$Type;
    ["contracts/Swap.sol:dxfc"]: dxfc$Type;
  }
}
